Add ContainerName
kubescape/operator pull request #242
Opened 2024-08-25 12:55 UTC by jnathangreeg

## Overview
This PR fixes #

**[Signed Commits](../CONTRIBUTING.md#sign-off-per-commit)**
- [x] Yes, I signed my commits.

2024-08-25 14:41 UTC, amitschendel requested changes

2024-08-25 14:41 UTC, amitschendel commented on admission/rules/v1/helpers.go
> +// GetContainerNameFromEvent returns the container name from the admission event.
```go
import (
	"k8s.io/api/admission/v1beta1"
	corev1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// getContainerNameFromExecToPodEvent returns the container name from the admission event for exec operations.
func getContainerNameFromExecToPodEvent(event v1beta1.AdmissionReview) string {
	if event.Request.SubResource == "exec" {
		if event.Request.Object.Raw != nil {
			podExecOptions := &corev1.PodExecOptions{}
			if err := runtime.DecodeInto(runtime.UnstructuredJSONScheme, event.Request.Object.Raw, podExecOptions); err == nil {
				return podExecOptions.Container
			}
		}
	}
	return ""
}

// getContainerNameFromPortForwardEvent returns the container name from the admission event for port-forward operations.
func getContainerNameFromPortForwardEvent(event v1beta1.AdmissionReview) string {
	if event.Request.SubResource == "portforward" {
		if event.Request.Object.Raw != nil {
			portForwardOptions := &corev1.PodPortForwardOptions{}
			if err := runtime.DecodeInto(runtime.UnstructuredJSONScheme, event.Request.Object.Raw, portForwardOptions); err == nil {
				return portForwardOptions.Container
			}
		}
	}
	return ""
}
```

2024-08-25 15:29 UTC, idohuber approved these changes

2024-08-26 06:51 UTC, matthyx approved these changes
thanks for fixing it 👍

2024-08-26 07:04 UTC, merged